steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vana-personal-server:$COMMIT_SHA', '.']
    dir: '.'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vana-personal-server:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/vana-personal-server:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/vana-personal-server:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vana-personal-server:latest']

images:
  - 'gcr.io/$PROJECT_ID/vana-personal-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vana-personal-server:latest' 